# Generated by Django 4.2.11 on 2024-04-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='audio',
            field=models.FileField(default=0, upload_to='audio/'),
            preserve_default=False,
        ),
    ]
